---
title: "COMP4010 - Homework 2"
output:
  pdf_document: default
  html_document: default
date: "2024-03-31"
---

# Homework 2

```{r}
library(tidyverse)
library(ggridges)
library(showtext)
library(scales)
```

```{r}
font_add_google("Open Sans")
showtext_auto()
main_font = "Open Sans"

college_palette <- c("#78d6ff", "#ffee54", "#992212", "#117024")

theme_vinuni <- function(base_size = 11, base_family = main_font, 
                         base_line_size = base_size / 22, 
                         base_rect_size = base_size / 22){
  theme_minimal(
    base_family = base_family,
    base_size = base_size,
    base_line_size = base_line_size,
    base_rect_size = base_rect_size
  ) +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(hjust = 0.5, face="bold"),
    plot.subtitle = element_text(hjust = 0.5, face="bold"),
    legend.position = "bottom",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "#bbbbbb", linewidth = 0.2),
    panel.grid.minor.y = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(size = rel(1.0), face = "bold"),
    legend.text = element_text(size = rel(0.9)),
    scale_fill_manual(values = college_palette)
  )
}

```


## Task 1.

```{r}
df <- read.csv("college_data_normalized.csv")

ggplot(df, aes(x = pct, y = college, fill = college)) + geom_density_ridges() +
  labs(x = "Percent of students admitted", y = "College",
  title = "Distribution of Percentage of Enrolled Students by College") +
  scale_fill_manual(values = college_palette, name = "College") +
  theme_vinuni() 
```

CECS often admits the smallest percentage of candidates, while CBM oftens admits the largest.

## Task 2.

```{r}
df_2118 <- df[df$year == 2118,]

ggplot(df_2118, aes(x = college, y = pct, fill = college)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = scales::percent(pct)), vjust = -0.5) + 
  scale_fill_manual(values = college_palette, name = "College") +
  theme_vinuni() +
  scale_y_continuous(labels = label_percent()) +
  labs(x = "College", y = "Percentage",
  title = "Percentage of Enrolled Students by College in 2118")
```

## Task 3.

```{r}
df_2118 <- df[df$year == 2118,]

ggplot(df_2118, aes(x = "", y = pct, fill = college)) +
  geom_bar(stat = "identity", color = "black") +
  coord_polar(theta = "y") + 
  geom_text(aes(label = scales::percent(pct)), position = position_stack(vjust = 0.5)) + 
  scale_fill_manual(values = college_palette, name = "College") +
  theme_vinuni() +
  theme(axis.title = element_blank()) +
  labs(title = "Percentage of Enrolled Students by College in 2118")
```

## Task 4.


```{r}
file_list <- list.files(pattern = "Viet Nam-")

for (file in file_list){
  file_df = read.csv(file)
  year = substring(file, 10, 13)
  file_df$Age <- factor(file_df$Age, levels = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89", "90-94", "95-99", "100+"))
  total <- (sum(file_df$M) + sum(file_df$F))
  file_df$M <- file_df$M * (-1) / total
  file_df$F <- file_df$F / total
  plot <- ggplot(file_df, aes(x = Age)) + 
    geom_bar(aes(y = M), stat = "identity", fill = "#112e80") + 
    geom_text(aes(y = M, label = scales::percent(abs(M))), hjust = 1.25) + 
    geom_bar(aes(y = F), stat = "identity", fill = "#109466") +
    geom_text(aes(y = F, label = scales::percent(F)), hjust = -0.25) + 
    scale_y_continuous(
    labels = abs, 
    limits = max(min(file_df$M) * -1, max(file_df$F)) * c(-1.25, 1.25)
    ) +
    theme_vinuni() +
    theme(panel.grid.major.y = element_blank()) +
    labs(x = "Age Group", y = "Percentage of Total Population",
    title = paste("Population Pyramid of Viet Nam - ", year)) + 
    coord_flip()
  
  print(plot)
}
```



